//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimuRdp.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HimuRdpResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HimuRdpResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HimuRdp.Core.Resources.HimuRdpResource", typeof(HimuRdpResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright (c) 2023-2024 HimuQAQ, all rights reserved. 的本地化字符串。
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] rdpclip6032 {
            get {
                object obj = ResourceManager.GetObject("rdpclip6032", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] rdpclip6034 {
            get {
                object obj = ResourceManager.GetObject("rdpclip6034", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] rdpclip6132 {
            get {
                object obj = ResourceManager.GetObject("rdpclip6132", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] rdpclip6164 {
            get {
                object obj = ResourceManager.GetObject("rdpclip6164", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ; RDP Wrapper Library configuration
        ///; Do not modify without special knowledge
        ///; Edited by sebaxakerhtc
        ///
        ///[Main]
        ///Updated=2024-06-28
        ///LogFile=\rdpwrap.txt
        ///SLPolicyHookNT60=1
        ///SLPolicyHookNT61=1
        ///
        ///[SLPolicy]
        ///TerminalServices-RemoteConnectionManager-AllowRemoteConnections=1
        ///TerminalServices-RemoteConnectionManager-AllowMultipleSessions=1
        ///TerminalServices-RemoteConnectionManager-AllowAppServerMode=1
        ///TerminalServices-RemoteConnectionManager-AllowMultimon=1
        ///TerminalServices-RemoteConnectionManager-MaxUs [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string rdpwrap {
            get {
                return ResourceManager.GetString("rdpwrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] rdpwrap32 {
            get {
                object obj = ResourceManager.GetObject("rdpwrap32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] rdpwrap64 {
            get {
                object obj = ResourceManager.GetObject("rdpwrap64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] rfxvmt32 {
            get {
                object obj = ResourceManager.GetObject("rfxvmt32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] rfxvmt64 {
            get {
                object obj = ResourceManager.GetObject("rfxvmt64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
